# https://hub.docker.com/_/nginx

version: '3.7'

name: scrolling-led-sign-website  # project name (aka stack)

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data