# # Overview
# set up website, database, and API

version: '3.7'

name: ${PROJECT_NAME}  # project name (aka stack)

services:

  # login with:
  # `docker exec -it ${CONTAINER_NAME} psql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -W`
  # once in `psql`, quit with `\q`
  postgres:
    image: postgres:16.1
    container_name: ${PROJECT_NAME}-db

    ports:
      - "5432:5432"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    volumes:
      - ./db:/var/lib/postgresql/data