# # Overview
# set up website, database, and API

version: '3.7'

name: ${PROJECT_NAME}  # project name (aka stack)

services:

  # # db
  # database
  # * login with:<br>
  # `docker exec -it ${CONTAINER_NAME} psql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -W`
  # * once in `psql`, quit with `\q`
  db:
    build: ./db  # build with `docker-compose build`

    container_name: ${PROJECT_NAME}-db

    restart: always

    ports:
      - "5432:${POSTGRES_PORT}"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    volumes:
      - ./db/data:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 3s
      retries: 3

    networks:
      - sls

  # # api
  # fastapi backend for interacting with database
  api:
    build: ./api  # build with `docker-compose build`

    container_name: ${PROJECT_NAME}-api

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - ${PORT_API}:8000

    # TODO: fix the health check (it was preventing Treafik from processing the labels)
    # healthcheck:
    #   test: curl http://localhost:${PORT_APP}/healthcheck || exit 1
    #   # TODO: can pytest be used here instead?
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 2m

    networks:
      - sls
      - web

  # # app
  # streamlit frontend for interacting with database
  app:
    build: ./app  # build with `docker-compose build`

    container_name: ${PROJECT_NAME}-app

    depends_on:
      - db
      - api

    env_file:
      - .env

    ports:
      - ${PORT_APP}:8501

    networks:
      - sls
      - web

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      
      # routers

      ## http
      - "traefik.http.routers.scrolling-led-sign.entrypoints=web"
      - "traefik.http.routers.scrolling-led-sign.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"

      ## https
      - "traefik.http.routers.scrolling-led-sign-secure.entrypoints=websecure"
      - "traefik.http.routers.scrolling-led-sign-secure.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.scrolling-led-sign-secure.tls=true"
      - "traefik.http.routers.scrolling-led-sign-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.scrolling-led-sign-secure.service=scrolling-led-sign"

      # middlewares
      - "traefik.http.routers.scrolling-led-sign.middlewares=https-redirect@file"
      - "traefik.http.routers.scrolling-led-sign-secure.middlewares=csrf@file"

      # services
      - "traefik.http.services.scrolling-led-sign.loadbalancer.server.scheme=https" 
      - "traefik.http.services.scrolling-led-sign.loadbalancer.server.port=8501"

networks:
  sls:
  web:
    external: true