services:
  web: 
    
    # build
    build:
      context: app
      target: builder

    container_name: scrolling-led-sign-website

    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT

    ports:
      - '8000:8000'