# # Overview
# set up website, database, and API

# # Todo
# * add python api to pull from and update database
# * add fastui website to add to database

version: '3.7'

name: ${PROJECT_NAME}  # project name (aka stack)

services:

  # # db
  # database
  # * login with:<br>
  # `docker exec -it ${CONTAINER_NAME} psql -d ${POSTGRES_DB} -U ${POSTGRES_USER} -W`
  # * once in `psql`, quit with `\q`
  db:
    image: postgres:16.1
    container_name: ${PROJECT_NAME}-db

    restart: always

    ports:
      - "5432:${POSTGRES_PORT}"
    
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    
    volumes:
      - ./db:/var/lib/postgresql/data

  # # api
  # fastapi backend for interacting with database
  api:
    build: ./api
    command: uvicorn main:app --host=0.0.0.0

    container_name: ${PROJECT_NAME}-api

    depends_on:
      - db

    env_file:
      - .env

    ports:
      - 8000:8000

    volumes:
      - ./api:/usr/src/api