[browser]
gatherUsageStats = false

[server]

# Due to conflicts between CORS and XSRF, if `server.enableXsrfProtection` is
# on and `server.enableCORS` is off at the same time, we will prioritize
# `server.enableXsrfProtection`.

# CORS
# https://github.com/joeychrys/streamlit_deployment/blob/main/compose/streamlit/Dockerfile
# default = true
enableCORS = false

# XSRF
# default = true
enableXsrfProtection = false